name: 'Article Count Workflow'
author: 'Estee Tey'
description: 'Allows you to show the number of articles that you have published on your github profile'

inputs:
  gh_token:
    description: 'GitHub access token with Repo scope'
    required: false
    default: ${{ github.token }}
  redirect_link:
    description: 'Link to redirect user when they click on the badge'
    default: ''
    required: false
  feed_list:
    description: "Comma separated list of RSS feed urls"
    default: ""
    required: true
  readme_path:
    description: 'Comma separated paths of the readme files you want to update'
    default: './README.md'
    required: false
  comment_tag_name:
    description: "Override the default comment tag name, if you want to show multiple instances of the action on the same repo"
    default: 'ARTICLE_BADGE'
    required: false


runs:
  using: composite
  steps:
  - name: Running Gautam's Blog post workflow 
    uses: gautamkrishnar/blog-post-workflow@master
    id: blog-post-workflow
    with:
      comment_tag_name: ${{inputs.comment_tag_name}}
      commit_message: "Updated Badge with latest number of articles"
      feed_list: ${{inputs.feed_list}}
      max_post_count: 1000000
      output_only: true
  - name: Counting articles
    uses: actions/setup-node@v2
    with:
      node-version: '14'
      articles: ${{fromJson(steps.blog-post-workflow.outputs.results)}}
      redirect_link: ${{inputs.redirect_link}}
    shell: bash
    run: |
      npm install
      node articleCount.js
      
        
      
branding:
  icon: 'activity'
  color: 'blue'