name: 'Article Count Workflow'
author: 'Estee Tey'
description: 'Allows you to show the number of articles that you have published on your profile'

inputs:
  feed_list:
    description: "Comma separated list of RSS feed urls"
    required: true
  gh_token:
    description: "GitHub access token with Repo scope"
    required: false
    default: ${{ github.token }}
  redirect_link:
    description: "Link to redirect user when they click on the badge. If not provided, the badge will not be a clickable."
    required: false
  readme_path:
    description: "Path of the readme file you want to update"
    default: README.md
    required: false
  comment_tag_name:
    description: "Override the default comment tag name, if you want to show multiple instances of the action on the same repo"
    default: ARTICLE_BADGE
    required: false
  tag_post_pre_newline:
    description: "To append with newline or not"
    default: "false"
    required: false
  badge_style:
    description: "Style of badge to be applied, refer to Shields.io website for the styles they offer"
    default: 'flat-square'
    required: false
  badge_label:
    description: "Text to be shown on the left side of the badge (label)"
    default: blog
    required: false
  badge_logo:
    description: "Logo to be shown on the left side of the badge (label)"
    default: ""
    required: false
  badge_message_suffix:
    description: "Text to be appended as suffix to the right side of the badge (message). For example, a suffix of 'pieces' will result in a message showing '20 pieces'"
    default: articles
    required: false
  badge_message_bg_color:
    description: "Background color of the right side of the badge (message). Accepts colors like 'green', hex values like '#F9D3C6'"
    default: "green"
    required: false

runs:
  using: composite
  steps:
  - name: Checkout
    uses: actions/checkout@v2
  - name: Running Gautam's Blog post workflow 
    uses: gautamkrishnar/blog-post-workflow@master
    id: blogpost_workflow
    with:
      feed_list: ${{inputs.feed_list}}
      max_post_count: 1000000
      output_only: true
  - name: Saves count as an output
    shell: bash
    id: count-step
    run: echo "::set-output name=articles_length::$(jq '. | length' /tmp/blog_post_workflow_output.json)"
  - name: Set up node
    uses: actions/setup-node@v2
    with:
      node-version: '14'
  - name: Generate Badge
    shell: bash
    env:
      articles_length: ${{ fromJSON(steps.count-step.outputs.articles_length) }}
      redirect_link: ${{inputs.redirect_link}}
      comment_tag_name: ${{inputs.comment_tag_name}}
      readme_path: ${{inputs.readme_path}}
      badge_style: ${{inputs.badge_style}}
      badge_label: ${{inputs.badge_label}}
      badge_logo: ${{inputs.badge_logo}}
      badge_message_bg_color: ${{inputs.badge_message_bg_color}}
      badge_message_suffix: ${{inputs.badge_message_suffix}}
    run: |
      cd ${{github.action_path}} && npm install && node articleCount.js
  - uses: stefanzweifel/git-auto-commit-action@v4
    with:
      commit_message: Update Article Count Badge
      commit_user_name: Article Count Badge Generator Action # defaults to "GitHub Actions"
      commit_user_email: hehe@lyqht.github.io # defaults to "actions@github.com"
      commit_author: Github Action Bot <actions@github.com> # defaults to author of the commit that triggered the run
      
branding:
  icon: 'activity'
  color: 'blue'