name: 'Article Count Workflow'
author: 'Estee Tey'
description: 'Allows you to show the number of articles that you have published on your github profile'

inputs:
  gh_token:
    description: 'GitHub access token with Repo scope'
    required: false
    default: ${{ github.token }}
  redirect_link:
    description: 'Link to redirect user when they click on the badge'
    default: ''
    required: false
  feed_list:
    description: "Comma separated list of RSS feed urls"
    default: ""
    required: true
  readme_path:
    description: 'Path of the readme file you want to update'
    default: 'README.md'
    required: false
  comment_tag_name:
    description: "Override the default comment tag name, if you want to show multiple instances of the action on the same repo"
    default: 'ARTICLE_BADGE'
    required: false


runs:
  using: composite
  steps:
  - name: Checkout
    uses: actions/checkout@v2
  - name: Running Gautam's Blog post workflow 
    uses: gautamkrishnar/blog-post-workflow@master
    id: blogpost_workflow
    with:
      comment_tag_name: ${{inputs.comment_tag_name}}
      commit_message: "Updated Badge with latest number of articles"
      feed_list: ${{inputs.feed_list}}
      max_post_count: 1000000
      output_only: true
  - name: Saves count as an output
    shell: bash
    id: count-step
    run: echo "::set-output name=articles_length::$(jq '. | length' /tmp/blog_post_workflow_output.json)"
  - name: Set up node
    uses: actions/setup-node@v2
    with:
      node-version: '14'
  - name: Generate Badge
    shell: bash
    env:
      articles_length: ${{ fromJSON(steps.count-step.outputs.articles_length) }}      
      redirect_link: ${{inputs.redirect_link}}
      readme_path: ${{inputs.readme_path}}
    run: |
      cd ${{github.action_path}} && npm install && node articleCount.js
  - uses: stefanzweifel/git-auto-commit-action@v4
    with:
      commit_message: Update Article Count Badge
      commit_user_name: Article Count Badge Generator Action # defaults to "GitHub Actions"
      commit_user_email: hehe@lyqht.github.io # defaults to "actions@github.com"
      commit_author: Github Action Bot <actions@github.com> # defaults to author of the commit that triggered the run
      
        
      
branding:
  icon: 'activity'
  color: 'blue'